from ..resources.resolve_path import resolve_path

map1 =  resolve_path('kenney_sokoban/map1.tmx')
map2 = resolve_path('kenney_sokoban/map2.tmx')
map3 = resolve_path('kenney_sokoban/map3.tmx')
map4 = resolve_path('kenney_sokoban/map4.tmx')
map5 = resolve_path('kenney_sokoban/map5.tmx')
map6 = resolve_path('kenney_sokoban/map6.tmx')
map7 = resolve_path('kenney_sokoban/map7.tmx')
map8 = resolve_path('kenney_sokoban/map8.tmx')
map9 = resolve_path('kenney_sokoban/map9.tmx')
map10 = resolve_path('kenney_sokoban/map_linear10.tmx')
map11 = resolve_path('kenney_pirate/map11.tmx')
map12 = resolve_path('kenney_pirate/map12.tmx')
map13 = resolve_path('kenney_pirate/map13.tmx')
map14 = resolve_path('kenney_pirate/map14.tmx')
map15 = resolve_path('kenney_pirate/map15.tmx')
map16 = resolve_path('kenney_pirate/map16.tmx')
map17 = resolve_path('kenney_pirate/map17.tmx')
map18 = resolve_path('kenney_pirate/map18.tmx')
map19 = resolve_path('kenney_pirate/map19.tmx')
map20 = resolve_path('kenney_pirate/map20.tmx')
