from ..resources.resolve_path import resolve_path

map1 =  resolve_path('kenney_sokoban/map_loop1.tmx')
map2 = resolve_path('kenney_sokoban/map_loop2.tmx')
map3 = resolve_path('kenney_sokoban/map_loop3.tmx')
map4 = resolve_path('kenney_sokoban/map_loop4.tmx')
map5 = resolve_path('kenney_sokoban/map_loop5.tmx')
map6 = resolve_path('kenney_sokoban/map_loop6.tmx')
map7 = resolve_path('kenney_sokoban/map_loop7.tmx')
map8 = resolve_path('kenney_sokoban/map_loop8.tmx')
map9 = resolve_path('kenney_sokoban/map_loop9.tmx')
map10 = resolve_path('kenney_sokoban/map_loop10.tmx')
map11 = resolve_path('kenney_pirate/map_loop11.tmx')
map12 = resolve_path('kenney_pirate/map_loop12.tmx')
map13 = resolve_path('kenney_pirate/map_loop13.tmx')
map14 = resolve_path('kenney_pirate/map_loop14.tmx')
map15 = resolve_path('kenney_pirate/map_loop15.tmx')
map16 = resolve_path('kenney_pirate/map_loop16.tmx')
map17 = resolve_path('kenney_pirate/map_loop17.tmx')
map18 = resolve_path('kenney_pirate/map_loop18.tmx')
map19 = resolve_path('kenney_pirate/map_loop19.tmx')
map20 = resolve_path('kenney_pirate/map_loop20.tmx')
